version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  #install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    #runtime-versions:
      # name: version
      # name: version
    #commands:
      # - command
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - pwd
      - zip -r LF1-index-photos-test.zip .
      - zip -r LF2-search-photos-test.zip .
      - pwd
      - aws s3 sync "./LF1-index-photos-test.zip" "s3://hw2-cloud-dc4676-deploy/"
      - aws s3 sync "./LF2-search-photos-test.zip" "s3://hw2-cloud-dc4676-deploy/"
      # - command
  post_build:
    commands:
      - aws lambda update-function-code \--function-name  LF1-index-photos \--s3-bucket hw2-cloud-dc4676-deploy --s3-key LF1-index-photos.zip
      - aws lambda update-function-code \--function-name  LF2-search-photos \--s3-bucket hw2-cloud-dc4676-deploy --s3-key LF2-search-photos.zip
      # - command
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths